name: Publish PSubShell.ps1
run-name: ${{ github.actor }} is publishing PSubShell.ps1 🚀
on: [push]
jobs:
  build:
    name: Run build.ps1 build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          ./build.ps1 build
        shell: pwsh
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          ./build.ps1 publish
        shell: pwsh
